# Generated by Django 4.1 on 2024-05-15 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='torrent_link',
            field=models.CharField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'magnet'])]),
        ),
    ]
